services:
  - type: web
    name: leviathan-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STAFF_ROLE_ID
        sync: false
      - key: CATEGORIA_TICKET_ID
        sync: false
      - key: CANAL_VENDAS_ID
        sync: false
      - key: CANAL_AVALIACOES_ID
        value: 1554485743278100602
      - key: CANAL_LOGS_ID
        sync: false
      - key: PIX_KEY
        value: ce767a59-4472-4fc8-8f5e-5189f97d6bf1
      - key: PIX_NOME
        value: Leviathan Accounts
      - key: CARGO_CLIENTE_ID
        sync: false
      - key: CARGO_VIP_ID
        sync: false
      - key: CARGO_MEGA_ID
        sync: false
      - key: CARGO_ULTRA_ID
        sync: false
      - key: CARGO_ETERNO_ID
        sync: false
